# Generated by Django 4.0.5 on 2022-07-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_done_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='name',
            field=models.CharField(default='NoName', max_length=50, verbose_name='Название'),
        ),
    ]
